var str = prompt('5 + 7 =')
alert('Sizning javobingiz ' + str)
var str = prompt('9 * 2 =')
alert('Sizning javobingiz ' + str)
var str = prompt('14 + 8 =')
alert('Sizning javobingiz ' + str)
var str = prompt('12 - 7 =')
alert('Sizning javobingiz ' + str)
var str = prompt('11 + 2 =')
alert('Sizning javobingiz ' + str)
var str = prompt('7 + 6 =')
alert('Sizning javobingiz ' + str)
var str = prompt('42 / 7 =')
alert('Sizning javobingiz ' + str)
var str = prompt('5 / 5 =')
alert('Sizning javobingiz ' + str)
var str = prompt('9 * 1 =')
alert('Sizning javobingiz ' + str)
var str = prompt('26 / 4 =')
alert('Sizning javobingiz ' + str)
var str = prompt('14 + 9 =')
